controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_joint
      - r_bigarm_joint
      - r_rotatearm_joint
      - r_elbow_joint
      - r_wrist_joint
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_joint
      - l_bigarm_joint
      - l_rotatearm_joint
      - l_elbow_joint
      - l_wrist_joint